# Generated by Django 5.2.8 on 2025-12-08 12:50

from django.db import migrations


def backfill_preferences(apps, schema_editor):
    """
    Create UserPreferences for all existing users who don't have one.
    
    PROF-009: Backfill existing users with default preferences:
    - email_important_updates = True (opt-out)
    - email_product_news = False (opt-in)
    """
    User = apps.get_model('auth', 'User')
    UserPreferences = apps.get_model('users', 'UserPreferences')
    
    # Get users without preferences
    users_without_prefs = User.objects.exclude(
        pk__in=UserPreferences.objects.values_list('user_id', flat=True)
    )
    
    # Bulk create preferences for existing users
    preferences_to_create = [
        UserPreferences(
            user=user,
            email_important_updates=True,
            email_product_news=False
        )
        for user in users_without_prefs
    ]
    
    if preferences_to_create:
        UserPreferences.objects.bulk_create(preferences_to_create)


def reverse_backfill(apps, schema_editor):
    """Reverse: Delete all UserPreferences (not typically used)."""
    pass  # Don't delete preferences on reverse


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_add_user_preferences'),
    ]

    operations = [
        migrations.RunPython(backfill_preferences, reverse_backfill),
    ]
