# Generated by Django 5.2.8 on 2025-11-10 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.app')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['app', 'timestamp'], name='analytics_e_app_id_42e212_idx'), models.Index(fields=['event_name'], name='analytics_e_event_n_b17a7e_idx'), models.Index(fields=['timestamp'], name='analytics_e_timesta_fdc538_idx')],
            },
        ),
    ]
