# Generated by Django 5.2.8 on 2025-11-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_event_app_version_event_locale_event_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
