# Generated by Django 5.2.8 on 2025-11-12 17:53

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs_for_existing_apps(apps, schema_editor):
    """Generate slugs for existing apps"""
    App = apps.get_model('analytics', 'App')
    for app in App.objects.all():
        if not app.slug:
            base_slug = slugify(app.name)
            slug = base_slug
            counter = 1
            while App.objects.filter(slug=slug).exclude(id=app.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            app.slug = slug
            app.save()


def add_unique_constraint(apps, schema_editor):
    """Add unique constraint to slug field using raw SQL to avoid index duplication."""
    # Django's AlterField tries to recreate the _like index which causes errors
    # We manually add only the unique constraint
    schema_editor.execute(
        'ALTER TABLE analytics_app ADD CONSTRAINT analytics_app_slug_key UNIQUE (slug);'
    )


def remove_unique_constraint(apps, schema_editor):
    """Remove unique constraint from slug field."""
    schema_editor.execute(
        'ALTER TABLE analytics_app DROP CONSTRAINT IF EXISTS analytics_app_slug_key;'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_app_user'),
    ]

    operations = [
        # Step 1: Add slug field (creates the _like index for SlugField)
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=False),
        ),
        # Step 2: Populate slugs for existing apps
        migrations.RunPython(generate_slugs_for_existing_apps, migrations.RunPython.noop),
        # Step 3: Add unique constraint manually (avoids Django recreating _like index)
        migrations.RunPython(add_unique_constraint, remove_unique_constraint),
    ]
