# Generated by Django 5.2.8 on 2025-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_make_user_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user_id', 'timestamp'], name='analytics_e_user_id_2b59cd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['app', 'user_id'], name='analytics_e_app_id_efefe0_idx'),
        ),
    ]
