# Generated by Django 5.2.8 on 2025-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_add_user_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='preferred_conversion_events',
            field=models.JSONField(blank=True, default=list, help_text='Event names to use as conversion events in analytics dashboards'),
        ),
    ]
