# Generated by Django 5.2.8 on 2025-12-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_add_preferred_conversion_events'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['app', 'event_name', 'timestamp'], name='analytics_e_app_id_90751c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['app', 'session_id', 'timestamp'], name='analytics_e_app_id_4e2e77_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['app', 'timestamp', 'country'], name='analytics_e_app_id_be42d9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['app', 'user_id', 'timestamp'], name='analytics_e_app_id_c4f58b_idx'),
        ),
    ]
