# Generated by Django 5.2.8 on 2025-12-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_add_composite_indexes_perf001'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='analytics_e_user_id_2b59cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='analytics_e_app_id_efefe0_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='analytics_e_app_id_c4f58b_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['app', 'session_id'], name='analytics_e_app_id_3eb8cb_idx'),
        ),
    ]
