# Generated by Django 5.2.8 on 2025-12-26 10:20
# Phase 7: Drop deprecated columns that are no longer stored
# These fields are accepted by API for backwards compatibility but not saved

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_remove_user_id_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='event',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='event',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='event',
            name='region',
        ),
        migrations.RemoveField(
            model_name='event',
            name='screen',
        ),
    ]
