# Generated by Django 5.2.8 on 2025-12-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_drop_deprecated_event_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
