# Generated by Django 5.2.8 on 2026-02-10 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_app_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('events_deleted', models.PositiveIntegerField()),
                ('filter_date_from', models.DateField()),
                ('filter_date_to', models.DateField()),
                ('filter_platform', models.CharField(blank=True, max_length=20, null=True)),
                ('filter_country', models.CharField(blank=True, max_length=2, null=True)),
                ('filter_event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to='analytics.app')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deletion Log',
                'verbose_name_plural': 'Deletion Logs',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
